mysite/CMdiagnose/urls.py
from django.urls import path
from rest_framework import routers

from . import views

app_name = 'CMdiagnose'
urlpatterns = [
    path('index', views.BootIndexView.as_view(), name='bootindex'),
    path('', views.IndexView.as_view(), name='index'),
    path('create1/', views.NewDetailView.as_view(), name='newdetail'),
    path('createh/', views.NewDetailViewh.as_view(), name='newdetailh'),
    path('createy/', views.NewDetailYao.as_view(), name='newdetailyao'),
    path('createx/', views.NewDetailXue.as_view(), name='newdetailxue'),
    path('new/', views.newPerson, name='new'),
    path('newext/', views.newCasesExt, name='newext'),
    path('newexth/', views.newHcasesExth, name='newexth'),
    path('searchc/', views.newCasesExt2, name='newext2'),
    path('newx/', views.newXue, name='newx'),
    path('searchx/', views.newXue2, name='newx2'),
    path('listx/', views.XueList.as_view(), name='newx3'),
    path('listy/', views.YaoList.as_view(), name='newy3'),
    path('listf/', views.FangList.as_view(), name='newy3'),
    path('zlistx/', views.zXueList.as_view(), name='newxz'),
    path('zlisty/', views.zYaoList.as_view(), name='newyz'),
    path('zlistf/', views.zFangList.as_view(), name='newyz'),
    path('newy/', views.newYao, name='newy'),
    path('searchy/', views.newYaoExt2, name='newyext2'),
    path('newyext/', views.newYaoExt, name='newyext'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:pk>/resultsh/', views.ResultsHcases.as_view(), name='resultsh'),
    path('<int:pk>/resultsy/', views.ResultsYao.as_view(), name='resultsy'),
    path('<int:pk>/resultsxue/', views.ResultsXue.as_view(), name='resultsxue'),
    path('<int:person_id>/tell/', views.tell, name='tell'),
    path('listxue', views.ListXue.as_view()),
    path('xue/<name>/', views.MatchXue.as_view()),
    path('yao/<name>/', views.MatchYao.as_view()),
    path('cases/<name>/', views.MatchCases.as_view()),
    path('listxue/<int:pk>/', views.DetailXue.as_view()),
    
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView



urlpatterns = [
	path('CMdiagnose/', include('CMdiagnose.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('google3f8df73d8e92caf2.html', TemplateView.as_view(template_name='google3f8df73d8e92caf2.html'), name='google3f8df73d8e92caf2'),
    path('', TemplateView.as_view(template_name='newdetailxue.html'), name='newdetailxue'),
    # path('api/', include('xue.urls')),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/CMdiagnose/views.py
from rest_framework import generics
from opencc import OpenCC
from rest_framework.response import Response
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from rest_framework.views import APIView
from rest_framework.decorators import api_view, renderer_classes
from rest_framework.renderers import JSONRenderer, StaticHTMLRenderer, TemplateHTMLRenderer
from .models import Body, Tongue, Person, Cases, Yao, Xue, Hcases
from .serializers import XueSerializer, YaoSerializer, CasesSerializer
from itertools import chain




class NewDetailView(generic.TemplateView):
    # https://docs.djangoproject.com/en/2.2/ref/class-based-views/generic-editing/#django.views.generic.edit.CreateView
    # model = Person
    template_name = 'CMdiagnose/newdetail.html'

class NewDetailViewh(generic.TemplateView):
    # https://docs.djangoproject.com/en/2.2/ref/class-based-views/generic-editing/#django.views.generic.edit.CreateView
    # model = Person
    template_name = 'CMdiagnose/newdetailh.html'

class NewDetailYao(generic.TemplateView):
    
    template_name = 'CMdiagnose/newdetailyao.html'

class NewDetailXue(generic.TemplateView):
    
    template_name = 'CMdiagnose/newdetailxue.html'

class DetailView(generic.DetailView):
    model = Person
    template_name = 'CMdiagnose/detail.html'


class ResultsView(generic.DetailView):
    model = Person
    template_name = 'CMdiagnose/results.html'

class ResultsHcases(generic.DetailView):
    model = Person
    template_name = 'CMdiagnose/resultsHcases.html'

class ResultsYao(generic.DetailView):
    model = Person
    template_name = 'CMdiagnose/resultsyao.html'

class ResultsXue(generic.DetailView):
    model = Person
    template_name = 'CMdiagnose/resultsxue.html'

class BootIndexView(generic.ListView):
    template_name = 'CMdiagnose/index.html'
    context_object_name = 'Person_list'
    def get_queryset(self):
        return Person.objects.all()

class IndexView(generic.ListView):
    template_name = 'CMdiagnose/index2.html'
    context_object_name = 'Person_list'
    def get_queryset(self):
        return Person.objects.all()

def tell(request, person_id):
    the_person = get_object_or_404(Person, pk=person_id)
    try:
        #envalue the Person object's body situation
        the_person.body.general = request.POST['general']
        # the_person = person.get(pk=request.POST['choice'])
    except (KeyError, Person.DoesNotExist):
        # Redisplay the person telling form.
        return render(request, 'CMdiagnose/detail.html', {
            'person': person,
            'error_message': "You didn't submit any symptoms.",
        })
    else:
        caselist=Cases.objects.all()
        the_person.body.result=''
        for case in caselist:
            case.case_check(the_person.body)
        the_person.body.save()
        the_person.tongue.save()
        the_person.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('CMdiagnose:results', args=(the_person.id,)))

def newPerson(request):
    b=Body()
    b.general=''
    b.general += request.POST['generalt']
    # b.general += request.POST['headt']
    # b.general += request.POST['wholet']
    # # b.general += request.POST['tongue_t']
    # b.general += request.POST['eyet']
    # b.general += request.POST['entt']
    # b.general += request.POST['neckt']
    # b.general += request.POST['backt']
    # b.general += request.POST['chestt']
    # b.general += request.POST['stomacht']
    # b.general += request.POST['lowerpartt']
    # b.general += request.POST['limbst']
    # b.general += request.POST['excrut']
    # b.general += request.POST['sleept']
    b.save()
    t=Tongue(body=b)

    
    #get tongue symptoms
    # t.tip += request.POST['t_tipt']
    # # t.root += request.POST['t_roott']
    # t.side += request.POST['t_sidet']
    # t.fur += request.POST['t_furt']
    # t.color += request.POST['t_colort']
    # t.moisture += request.POST['t_moisturet']
    # t.middle += request.POST['t_middlet']
    # t.bottom += request.POST['t_bottomt']
    
    # t_result=''
    # t_result=t.check_()

    #get body symptoms
    
    
    t.save()
    
    try:

        the_person = Person(body=b,tongue=t)
        # the_person.body.general = request.POST['general']
        # the_person = person.get(pk=request.POST['choice'])
    except (KeyError, the_person.DoesNotExist):
        # Redisplay the person telling form.
        return render(request, 'CMdiagnose/detail.html', {
            'person': person,
            'error_message': "You didn't submit any symptoms.",
        })
    else:
        print (the_person.body.general)
        
        caselist=Cases.objects.all()
        the_person.body.result=''
        # the_person.body.result=t_result
        for case in caselist:
            case.case_check(the_person.body)
        the_person.body.save()
        the_person.tongue.save()
        the_person.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('CMdiagnose:results', args=(the_person.id,)))

# def index(request):
#     return HttpResponse("欢迎光临笔花医镜电子诊断系统")

def newCasesExt(request):
    # b=Body()
    # b.general=''
    # b.general += request.POST['generext']

    # b.save()
    # t=Tongue(body=b)

    
    # t.save()
    
    try:

        the_person=Person.objects.all()[:1].get()
        the_person.body.general=''
        the_person.body.general = request.POST['generext']
        # the_person.body.general = request.POST['general']
        # the_person = person.get(pk=request.POST['choice'])
    except (KeyError, the_person.DoesNotExist):
        # Redisplay the person telling form.
        return render(request, 'CMdiagnose/detail.html', {
            'person': person,
            'error_message': "You didn't submit any symptoms.",
        })
    else:
        print (the_person.body.general)
        
        caselist=Cases.objects.all()
        the_person.body.result=''
        # the_person.body.result=t_result
        for case in caselist:
            case.case_checkext(the_person.body)

        genlist=[]
        genlist=[x.strip() for x in str(the_person.body.general).split(',')]
        genlist = [i for i in genlist if i] 
        for genele in set(genlist):
            the_person.body.result=the_person.body.result.replace(genele,'<mg>'+genele+'</mg>')
            
        the_person.body.save()
        the_person.tongue.save()
        the_person.save()

        return HttpResponseRedirect(reverse('CMdiagnose:results', args=(the_person.id,)))

def newHcasesExth(request):
    # b=Body()
    # b.general=''
    # b.general += request.POST['generext']

    # b.save()
    # t=Tongue(body=b)

    
    # t.save()
    
    try:

        the_person=Person.objects.all()[:1].get()
        the_person.body.general=''
        the_person.body.general = request.POST['generext']
        # the_person.body.general = request.POST['general']
        # the_person = person.get(pk=request.POST['choice'])
    except (KeyError, the_person.DoesNotExist):
        # Redisplay the person telling form.
        return render(request, 'CMdiagnose/detail.html', {
            'person': person,
            'error_message': "You didn't submit any symptoms.",
        })
    else:
        print (the_person.body.general)
        
        caselist=Hcases.objects.all()
        the_person.body.result=''
        # the_person.body.result=t_result
        for case in caselist:
            case.case_checkext(the_person.body)

        genlist=[]
        genlist=[x.strip() for x in str(the_person.body.general).split(',')]
        genlist = [i for i in genlist if i] 
        for genele in set(genlist):
            the_person.body.result=the_person.body.result.replace(genele,'<mg>'+genele+'</mg>')
            
        the_person.body.save()
        the_person.tongue.save()
        the_person.save()

        return HttpResponseRedirect(reverse('CMdiagnose:resultsh', args=(the_person.id,)))

def newCasesExt2(request):
    # b=Body()
    # b.general=''
    # b.general += request.POST['generext']

    # b.save()
    # t=Tongue(body=b)

    
    # t.save()
    
    try:

        the_person=Person.objects.all()[:1].get()
        the_person.body.general=''
        the_person.body.general = request.GET.get('q', '')
        # the_person.body.general = request.POST['general']
        # the_person = person.get(pk=request.POST['choice'])
    except (KeyError, the_person.DoesNotExist):
        # Redisplay the person telling form.
        return render(request, 'CMdiagnose/detail.html', {
            'person': person,
            'error_message': "You didn't submit any symptoms.",
        })
    else:
        print (the_person.body.general)
        
        caselist=Cases.objects.all()
        the_person.body.result=''
        # the_person.body.result=t_result
        for case in caselist:
            case.case_checkext(the_person.body)

        genlist=[]
        genlist=[x.strip() for x in str(the_person.body.general).split(',')]
        genlist = [i for i in genlist if i] 
        for genele in set(genlist):
            the_person.body.result=the_person.body.result.replace(genele,'<mg>'+genele+'</mg>')
            
        the_person.body.save()
        the_person.tongue.save()
        the_person.save()

        return HttpResponseRedirect(reverse('CMdiagnose:results', args=(the_person.id,)))


def newYao(request):
    b=Body()
    b.general=''
    b.general += request.POST['generalt']

mysite/CMdiagnose/templates/CMdiagnose/detail.html
<h1>{{ person.pk }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'CMdiagnose:tell' person.id %}" method="post">
{% csrf_token %}
<label>General Symptoms</label>
<input type="text" name="general" value=""><br>
<input type="submit" value="get result">
</form>

mysite/CMdiagnose/templates/CMdiagnose/fangprofile.html
<html><body>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'CMdiagnose/style3.css' %}">
        <a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:bootindex' %}">回首頁</a>
        <a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetailxue' %}">穴位搜索</a>
        <a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetailyao' %}">中藥搜索</a>
        <a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetail' %}">方劑搜索</a>
    <h1>方劑一覽</h1>
    
        {% for fang in fangs %}
        <div>
        
        ==============================================================================
        {% autoescape off %}
        <li>{{ fang.solution }}</li>
        
        <li>{{ fang.symptom }}</li>
        {% endautoescape %}
        
        </div>
        {% endfor %}

  
    </body></html>

mysite/CMdiagnose/templates/CMdiagnose/index2.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<p>本資料庫的內容來源繁雜，不及備載，僅供學術參考，不作商業用途，其著作權各歸其原作者或其出版社所有。若有真實疾患請尋求合法醫師，非中醫師請勿擅自處方服藥。</p>
<br>
<a href="{% url 'CMdiagnose:newdetailxue' %}">穴位搜索</a>
<br>
<a href="{% url 'CMdiagnose:newdetailyao' %}">中藥搜索</a>
<br>
<a href="{% url 'CMdiagnose:newdetail' %}">方劑搜索</a>
    <!-- <ul>
    {% for person in Person_list %}
        <li><a href="{% url 'CMdiagnose:detail' person.pk %}">{{ person.pk }}</a></li>
    {% endfor %}
    </ul> -->

mysite/CMdiagnose/templates/CMdiagnose/newdetailh.html
    {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'CMdiagnose/style3.css' %}">
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:bootindex' %}">回首頁</a>
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetailxue' %}">穴位搜索</a>
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetailyao' %}">中藥搜索</a>
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetail' %}">方劑搜索</a>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>中醫資源檢索系統</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'CMdiagnose/multi-select/css/multi-select.css' %}">
  <link href="/static/CMdiagnose/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <style>

    .RNNXgb {
      background: #fff;
      display: flex;
      /* border-radius: 8px; */
      border: 1px solid #dfe1e5;
      box-shadow: none;
      /* border-radius: 24px; */
      z-index: 3;
      height: 44px;
      margin: 0 auto;
      width: 500px;
    }
  </style>
  

<body>

     
  <p>本資料庫的內容來源繁雜，不及備載，僅供學術參考，不作商業用途，其著作權各歸其原作者或其出版社所有。若有真實疾患請尋求合法醫師，非中醫師請勿擅自處方服藥。</p>
  <br>
 
 
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'CMdiagnose:newexth' %}" method="post" id="my_form">
{% csrf_token %}

<div class="RNNXgb" align="center">
<!-- <label>General Symptoms</label> -->
<input type="text" id="generext" name="generext" size="70" placeholder='請輸入症狀名稱，方劑名稱，或所包含的漢字（簡繁體皆可，系統自帶簡轉繁功能）'>
&nbsp;
<button class="btn btn-primary" type="submit" value="載入">載入</button><br>
</div>
</br></br>

<div align="center" clsee="container3">


    <div align="center">
        <p>以下為症狀輔助查找系統，若您不熟悉症狀名稱，可任意打入一個漢字，與該字相關的症狀名稱將會在選項框中出現。</p>
        <p>當症狀名稱被選定後，關閉彈出的確認窗口，您選定的症狀名稱將出現在搜索欄。選項默認為繁體，可按鈕轉換為簡體。</p>
        簡繁轉化
        <a  id="translateLink" class="btn btn-success" href="javascript:translatePage();">简体</a>
    </div>


  <!-- ends -->
  <!-- jQuery -->
  <script src="/static/CMdiagnose/js/jquery.min.js"></script>
  <script src="/static/CMdiagnose/js/jquery.quicksearch.min.js"></script>
  <!-- Bootstrap JavaScript -->
  <script src="/static/CMdiagnose/js/bootstrap.min.js"></script>
  <script src="/static/CMdiagnose/js/jquery.multi-select.js"></script>
  <script src="/static/CMdiagnose/js/FontChange.js"></script>
  <script type="text/javascript">
  // run pre selected options



$('.searchable[name=general]').multiSelect({
  selectableHeader: "<input type='text' class='search-input' autocomplete='off' placeholder='嘗試輸入 \"炎\"'>",
  selectionHeader: "<input type='text' class='search-input' autocomplete='off'>",
  afterInit: function(ms){
    var that = this,
        $selectableSearch = that.$selectableUl.prev(),
        $selectionSearch = that.$selectionUl.prev(),
        selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
        selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

    that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
    .on('keydown', function(e){
      if (e.which === 40){
        that.$selectableUl.focus();
        return false;
      }
    });

    that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
    .on('keydown', function(e){
      if (e.which == 40){
        that.$selectionUl.focus();
        return false;
      }
    });
  },
  afterSelect: function(values){
    this.qs1.cache();
    this.qs2.cache();
    alert("Select value: "+values);
    document.getElementById("generext").value += values + "," ;
  },

  afterDeselect: function(){
    this.qs1.cache();
    this.qs2.cache();
    
    
  }
  
},

$('#my_form').submit(function(event) {
  event.preventDefault(); //this will prevent the default submit

  // document.getElementById("generext").value=Traditionalized(document.getElementById("generext").value);
  if (document.getElementById("generext").value.substr(-1)==','){
    document.getElementById("generext").value=document.getElementById("generext").value.slice(0, -1);
  }
  // your code here
  $(this).unbind('submit').submit(); // continue the submit unbind preventDefault
})
);
  </script>
</br></br></br>
</div>

</form>
<script type="text/javascript"> var infolinks_pid = 3197649; var infolinks_wsid = 0; </script> <script type="text/javascript" src="//resources.infolinks.com/js/infolinks_main.js"></script>

<!-- <form action="{% url 'CMdiagnose:newext' %}" method="post">
  {% csrf_token %}

  <label>Extreme Search by Symptoms</label>
  <input type="text" id="generext" name="generext" value=""><br>
  <input type="submit" value="載入">
</form> -->
<div align="left">
    API ：</br>
    穴位：aaronchen.pythonanywhere.com/CMdiagnose/zlistx/?q=XX</br>
    中藥：aaronchen.pythonanywhere.com/CMdiagnose/zlisty/?q=XX</br>
    方劑：aaronchen.pythonanywhere.com/CMdiagnose/zlistf/?q=XX</br>
    (只需將以上網址複製粘貼至地址欄：將"XX"改寫成對應症狀名稱即可直接得到搜索結果</br>
    例如：搜索關於“頭痛”的穴位：</br>
    僅需複製以下網址粘貼到瀏覽器的地址欄（中藥，方劑以此類推）</br>
    aaronchen.pythonanywhere.com/CMdiagnose/zlistx/?q=頭痛)</br>
</div>
</body>

mysite/CMdiagnose/templates/CMdiagnose/results.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'CMdiagnose/style3.css' %}">
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:bootindex' %}">回首頁</a>
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetailxue' %}">穴位搜索</a>
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetailyao' %}">中藥搜索</a>
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetail' %}">方劑搜索</a>
<body>
<h1>症狀：</h1>

<p>{{ person.body.general |linebreaks}}</p>

<h1>診斷結果：</h1>
<div>
<p>{% autoescape off %}{{ person.body.result |linebreaks}}{% endautoescape %}</p>
</div>
<script type="text/javascript"> var infolinks_pid = 3197649; var infolinks_wsid = 0; </script> <script type="text/javascript" src="//resources.infolinks.com/js/infolinks_main.js"></script>
</body>

mysite/CMdiagnose/templates/CMdiagnose/resultsHcases.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'CMdiagnose/style3.css' %}">
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:bootindex' %}">回首頁</a>
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetailxue' %}">穴位搜索</a>
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetailyao' %}">中藥搜索</a>
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetail' %}">方劑搜索</a>
<body>
<h1>症狀：</h1>

<p>{{ person.body.general |linebreaks}}</p>

<h1>診斷結果：</h1>
<div>
<p>{% autoescape off %}{{ person.body.result |linebreaks}}{% endautoescape %}</p>
</div>
<script type="text/javascript"> var infolinks_pid = 3197649; var infolinks_wsid = 0; </script> <script type="text/javascript" src="//resources.infolinks.com/js/infolinks_main.js"></script>
</body>

mysite/CMdiagnose/templates/CMdiagnose/resultsxue.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'CMdiagnose/style3.css' %}">
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:bootindex' %}">回首頁</a>
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetailxue' %}">穴位搜索</a>
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetailyao' %}">中藥搜索</a>
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetail' %}">方劑搜索</a>
<body>
<h1>穴位主治：</h1>

<p>{{ person.body.general |linebreaks}}</p>

<h1>相關穴位：</h1>
<div>
<p>{% autoescape off %}{{ person.body.result |linebreaks}}{% endautoescape %}</p>
</div>
<script type="text/javascript"> var infolinks_pid = 3197649; var infolinks_wsid = 0; </script> <script type="text/javascript" src="//resources.infolinks.com/js/infolinks_main.js"></script>
</body>

mysite/CMdiagnose/templates/CMdiagnose/resultsyao.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'CMdiagnose/style3.css' %}">
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:bootindex' %}">回首頁</a>
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetailxue' %}">穴位搜索</a>
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetailyao' %}">中藥搜索</a>
<a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetail' %}">方劑搜索</a>
<body>
<h1>藥性主治：</h1>

<p>{{ person.body.general |linebreaks}}</p>

<h1>藥品陳列：</h1>
<div>
<p>{% autoescape off %}{{ person.body.result |linebreaks}}{% endautoescape %}</p>
</div>
<script type="text/javascript"> var infolinks_pid = 3197649; var infolinks_wsid = 0; </script> <script type="text/javascript" src="//resources.infolinks.com/js/infolinks_main.js"></script>
</body>

mysite/CMdiagnose/templates/CMdiagnose/xueprofile.html
<html><body>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'CMdiagnose/style3.css' %}">
        <a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:bootindex' %}">回首頁</a>
        <a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetailxue' %}">穴位搜索</a>
        <a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetailyao' %}">中藥搜索</a>
        <a class="btn btn-primary js-scroll-trigger" href="{% url 'CMdiagnose:newdetail' %}">方劑搜索</a>
    <h1>穴位一覽</h1>
    
        {% for xue in xues %}
        {% autoescape off %}
    <div>
        
        =========={{ xue.name }}==========
        <p>
                {{ xue.responses }}
        </p>
        <p>  
        {{ xue.properties }}
        </p>


</div>
        {% endautoescape %}
    
        {% endfor %}
    
    </body></html>